### ISSUE TITLE
epic: Aire Management UI

### ISSUE THREAD

**Issue by josiahhaswell** [sunshower-io/zephyr-aire#2]
**Is your feature request related to a problem? Please describe.**
Zephyr needs a management UI with the following functionality:

- [ ] UI Chrome
- [ ] Auto-generation of forms
- [ ] Plugin/Cluster Topology Views
- [ ] Modify Plugin Lifecycle
- [ ] Add/Remove Plugins
- [ ] View Plugin State/Details
- [ ] Usage Statistics
- [ ] Strong development support via Gradle/Maven plugins

**Describe the solution you'd like**

Each component will be described in its totality in the corresponding sub-epic

**Comment by RangeMum** [comment]
If there is a way I can help, I'm not seeing it right now on GitHub at the
link above. ---------RM
